# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Category"
  pageRef = "categories"
  weight = 20
[[main]]
  name = "Tag"
  pageRef = "tags"
  weight = 30
[[main]]
  name = "About"
  pageRef = "about"
  weight = 40 

