baseURL: https://michaelchan.space
languageCode: en-us
theme: smigle
title: michael's space
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
    - identifier: about
      name: About
      url: /about/
      weight: 6
params:
  abbrDateFmt: Jan 2
  author: konomichael
  brandIconFile: images/avatar.jpg
  customStylesheets:
    # - css/custom.css
  dateFmt: 2006-01-02
  social:
    - name: GitHub
      url: https://github.com/konomichael
    - name: Email
      url: mailto:hi@michaelchan.space
  subtitle: Welcome to my space 👋
